// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "ebuy-ecommerce-app",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1yubs7wi9jmi5.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:36c7edf4-e74e-42b7-8667-77576515629a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0VokOABk4",
    "aws_user_pools_web_client_id": "1nh2j7eflfk37c5u2cmu7melvn",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "products",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "ebuyapi",
            "endpoint": "https://pli1a7m6bh.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
